version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: boi-pora-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: boi-pora

volumes:
  mongodb_data:
